In [7]:
import numpy as np

#using reshape() method
arr = np.array([1,2,3,4,5,6])
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)

#using np.reshape() function
arr = np.array([1,2,3,4,5,6])
reshaped_arr = np.reshape(arr, (3,2))
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [11]:
import pandas as pd
mydataset = {
    'cars':["BMW", "Volvo","Tesla"],
    'passings':[3,7,2]
}

myvar = pd.DataFrame(mydataset)
print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2  Tesla         2
